config/routes.rb
Rails.application.routes.draw do
  resources :widgets
  resources :homes
  resources :products

   root 'homes#index'
   resources :customers
   resources :orders do 
        resources :order_items 
      end

   get '/today_orders' => 'homes#today_orders'
   get '/render_customer_data' => 'orders#render_customer_data'
   get 'typeahead/:query' => 'customers#typeahead'

   get 'order_by_date' => 'reports#order_by_date'
   get 'order_items_by_date' => 'reports#order_items_by_date'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :orders
	  accepts_nested_attributes_for :orders, :allow_destroy => true
	    validates :first_name, presence: true
	  #before_create :set_lat_and_lng

	  def set_lat_and_lng
	  	 self.lat =  rand(-90.000000000...90.000000000)
	  	 self.lng =   rand(-180.000000000...180.000000000)
	  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	before_action :set_customer , only:[:show , :edit , :update, :destroy]


	def index
		@customers = Customer.all 
	end 
	
	def edit

	end

	def show

	end
	
	def new
		@customer = Customer.new
		
	end
	
	def create
		@customer = Customer.new(customer_params)
		respond_to do |format|
			if @customer.save
				format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        	else
        		format.html { render :new }
        		format.json { render json: @customer.errors.messages.values.join(','), status: :unprocessable_entity }
       		end
       	end
	end
	
	def update
	  respond_to do |format|
	    if @customer.update(customer_params)
	      format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
	      format.json { render :show, status: :ok, location: @customer }
	   else
	      format.html { render :edit }
	      format.json { render json: @customer.errors.messages.values.join(','), status: :unprocessable_entity }
	   end
	  end
   end

   def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  	def typeahead
  		
  		render json: Customer.where('first_name like ?', "#{params[:query]}%")

  	end
	
	private
	
	def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :address_line1 , :address_line2, :city, :state, :zip_code, :lat, :lng)
    end
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customers/_form.html.erb
<%= form_for (@customer), html: {class: 'form-horizontal form-label-left', data: {"parsley-validate" => ""}} do |f| %>
  <%= f.hidden_field :lat %>
  <%= f.hidden_field :lng %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@customer.errors.count, "error")} prohibited this customer from being saved:" %>
      </h2>
      <ul>
        <% @customer.errors.full_messages.each do |msg| %>
          <li>
            <%= msg      %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-lg-6 col-md-6">
      <div class="form-group">
        <label class="control-label col-md-4 col-xs-12" for="first-name">First Name</label>
        <div class="col-md-8 col-xs-12">
          <%= f.text_field :first_name, class: 'form-control col-md-8 col-xs-12', required: true %>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-md-4 col-xs-12" for="first-name">Last Name</label>
        <div class="col-md-8 col-xs-12">
          <%= f.text_field :last_name, class: 'form-control col-md-8 col-xs-12', required: true %>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-md-4 col-xs-12" for="first-name">Address Line 1</label>
        <div class="col-md-8 col-xs-12">
          <%= f.text_field :address_line1, class: 'form-control col-md-8 col-xs-12' , required: true  %>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-md-4 col-xs-12" for="first-name">Address Line 2</label>
        <div class="col-md-8 col-xs-12">
          <%= f.text_field :address_line2, class: 'form-control col-md-8 col-xs-12' %>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-md-4 col-xs-12" for="first-name">City</label>
        <div class="col-md-8 col-xs-12">
          <%= f.text_field :city, class: 'form-control col-md-8 col-xs-12' , required: true%>
        </div>
      </div>

      <div class="form-group">
        <label class="control-label col-md-4 col-xs-12" for="first-name">State</label>
        <div class="col-md-8 col-xs-12">
          <%= f.text_field :state, class: 'form-control col-md-8 col-xs-12', required: true , :onChange => "getAddress()" %>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-md-4 col-xs-12" for="first-name">Zip Code</label>
        <div class="col-md-8 col-xs-12">
          <%= f.text_field :zip_code, class: 'form-control col-md-8 col-xs-12' %>
        </div>
      </div>
      <div class='form-group'>
        <div class="text-center">
          <%= f.submit 'Save Customer' , class:'btn btn-primary' %>
        </div>

      </div>    
    </div>
    <div class="col-lg-6 col-md-6">
    <div id="map" style="width:100%;height:600px">
      <%= render partial: 'shared/map' , locals: { lat: @customer.lat , lng: @customer.lng  , state: @customer.state , address_line: @customer.try(:address_line1) , :order_num => @customer.orders.first.try(:order_num)} %>
    </div>
    </div>
  </div>
<% end %>

<script>
jQuery(document).ready(function(){
  jQuery('customer_address_line1').focus();
  jQuery('customer_address_line2').focus();
  jQuery('city').focus();
  jQuery('state').focus();

})

 var getAddress = function getAddress(){
  var address = jQuery('#customer_address_line1').val()
  var address2 = jQuery('#customer_address_line2').val()
  var city = jQuery('#customer_city').val()
  var state = jQuery('#customer_state').val()
  
    jQuery.getJSON( {
      url  : 'https://maps.googleapis.com/maps/api/geocode/json',
      data : {
          sensor  : false,
          address : address,
          city: city,
          state: state
      },
      success : function(response) {
        
          
          var lat = response.results[0].geometry.location.lat
          var lng= response.results[0].geometry.location.lng
          
          
          
          jQuery('#customer_lat').val(lat)
          jQuery('#customer_lng').val(lng)
          myMap(lat , lng );
          
      },
      error: function(e){
        alert("Please Enter Proper Address");
      }
    
 });
}
</script>

app/views/customers/_map.html.erb
<script src="https://maps.googleapis.com/maps/api/js"></script>
<script type="text/javascript">
  jQuery(document).ready(function(){
  	setMap();
  	myMap();
  	
  })
</script>

app/views/customers/_new_map.html.erb
  <div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:600px;">
          <div class="x_content">
            <div class="container-fluid" style="margin-top: 100px">
              <div id="map" style="width:100%;height:600px"></div>

              <script>
              function myMap() {
                var mapCanvas = document.getElementById("map");
                var lat = <%= @customer.try(:lat) %>
                var lng = <%= @customer.try(:log) %>
                
                if (lat == null && lng == null){
                   var mapOptions = {
                    center: new google.maps.LatLng(0,0),
                  zoom: 2
                  };
              }else{
                 var mapOptions = {
                  center: new google.maps.LatLng(lat,lng),
                  zoom: 5
               };
              }
                var map = new google.maps.Map(mapCanvas, mapOptions);

                
                var beachMarker = new google.maps.  Marker({
                           position: {lat: lat, lng: lng},
                  map: map,
                  title: "<%= @customer.try(:address_line1) %>,<%= @customer.try(:address_line2) %>,<%= @customer.try(:city) %>,<%= @customer.try(:state) %>" 

                 });
              }
              </script>

              <script src="https://maps.googleapis.com/maps/api/js"></script>
            </div>
          </div>
        </div>
      </div>
  </div>             

app/views/customers/edit.html.erb
<div>
  <div class="page-title">
    <div class="title_left">
      <h3>Customer form</h3>
    </div>
    <div class="title_left">
      <h3>Cusormer</h3>
    </div>
    <div class="title_left">
      <h3>New Customer</h3>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel" style="height:600px;">
        <div class="x_content">
          <div class="container-fluid">
            <%= render partial: 'form' %>
          </div>
          <%= link_to 'Show', @customer , class: 'btn btn-primary'%> |
          <%= link_to 'Back', customers_path , class: 'btn btn-success' %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/customers/index.html.erb
	<div class="clearfix"></div>
	  <div class="row">
	    <div class="col-md-12 col-sm-12 col-xs-12">
	      <div class="x_panel" style="height:600px;">
	        <div class="x_content">
	          <div class="container-fluid" style="margin-top: 100px;">
	  
	<h3>Listing Customers</h3>
	  <div class="table-responsive">          


		<table border="0" cellspacing="0" cellpadding="0" width="100%" class="table table-bordered">
		  <thead>
		    <tr class="success">
		      <th>Name</th>
		      <th>Last Name</th>
		      <th>Address Line1</th>
		      <th>Address Line2</th>
		      <th>City</th>
		      <th>State</th>
		      <th>Zip Code</th>
		      <th>Latitude</th>
		      <th>Longitude</th>
		      <th colspan="8"></th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @customers.each do |customer| %>
		      <tr >
		        <td><%= customer.first_name %></td>
		        <td><%= customer.last_name %></td>
		        <td><%= customer.address_line1 %></td>
		        <td><%= customer.address_line2 %></td>
		        <td><%= customer.city %></td>
		        <td><%= customer.state %></td>
		        <td><%= customer.zip_code %></td>
		        <td><%= customer.lat %></td>
		        <td><%= customer.lng %></td>
		        <td><%= link_to 'Show', customer , class: 'btn btn-success btn-xs' %></td>
		        <td><%= link_to 'Edit', edit_customer_path(customer) , class: 'btn btn-primary btn-xs' %></td>
		        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger btn-xs' %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>

	<br>

	<%= link_to 'New Customer', new_customer_path , class: 'btn btn-success' %>
	</div>

app/views/customers/new.html.erb
<div>
  <div class="page-title">
    <div class="title_left">
      <h3>Customer form</h3>
    </div>
    <div class="title_left">
      <h3>Cusormer</h3>
    </div>
    <div class="title_left">
      <h3>New Customer</h3>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel" style="height:600px;">
        <div class="x_content">
          <div class="container-fluid" >
            <%= render partial: 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customers/show.html.erb
<div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:600px;">
          <div class="x_content">
            <div class="container-fluid" style="margin-top: 100px">
              <div>
                <h2 class="section_heading_05 float_l">Customers Detail</h2>
  <div class="float_r mb-10-ie">
    <input type="button" value="Edit" class="button-link green-shadow btn_ht_cur" onclick="window.location.href ='<%= edit_customer_path(@customer) %>'"/>
  </div>
</div>
<div class="col-lg-6 col-md-6">
    <div class="clear"></div>
    <div class="table.responsive">
    <fieldset class="ui-corner-all bdr-ccc">
      <table class="table" border="0" width="100%">
        <tr>
          <td style="width:33%"><label>Name:</label>
            <%= @customer.first_name %>
          </td>

          <td style="width:33%" colspan="2"><label>Last Name:</label>
            <%= @customer.last_name %>
          </td>

        </tr>
        <tr>
          <td colspan="6" class="td_border" ><div class="div_bdr"></div></td>
        </tr>
        <tr>
          <td><label> Address 1: </label>
            <%= @customer ? @customer.address_line1 : ""%>
          </td>
          <td><label> Address 2:</label>
            <%= @customer ? @customer.address_line2 : ""%>
          </td>
          <td><label>City:</label>
            <%= @customer ? @customer.city : ""%>
          </td>
          <td><label>State: </label>
            <%= @customer ? @customer.state : ""%>
          </td>
          <td><label>Latitude: </label>
            <%= @customer ? @customer.lat : ""%>
          </td>
          <td><label>Longitude: </label>
            <%= @customer ? @customer.lng : ""%>
          </td>

        </tr>
        <tr>
          <td colspan="6" class="td_border" ><div class="div_bdr"></div></td>
        </tr>
        <tr>
          <td><label>Zip Code:</label>
            <%= @customer ? @customer.zip_code : ""%>
          </td>
        </tr>
        
       </table>
        
    </fieldset>
    </div>
</div>
<div class="col-lg-6 col-md-6">
<div id="map" style="width:100%;height:600px">
  <%= render partial: 'shared/map', locals: { :lat => @customer.lat , :lng => @customer.lng , :state => @customer.state , :address_line => @customer.address_line1 , :order_num => @customer.orders.first.try(:order_num) } %>

</div>
</div>



        </div>
    </div>
    </div>
    </div>
    </div>